# browsers
cask "arc"
cask "firefox"

# design
cask "figma"

# development
brew "bat"
brew "deno"
brew "eza"
brew "fish"
brew "fzf"
brew "gh"
brew "helix"
brew "lazygit"
brew "starship"
brew "zoxide"
cask "cursor"
cask "dbngin"
cask "handbrake"
cask "herd"
cask "imageoptim"
cask "minisim"
cask "polypane"
cask "transmit"
cask "visual-studio-code"
cask "wezterm"
cask "zed"

# fonts
cask "font-jetbrains-mono-nerd-font"

# others
cask "ankama" # 🎮
cask "discord"
cask "setapp"
cask "whatsapp" # 😩

# productivity
cask "obsidian"
cask "onlyoffice"
